#!/usr/bin/env bash

EDIT="vi"

if [[ $(command -v emacsclient) ]]; then
    EDIT="emacsclient -ta '' --server-file $HOME/.emacs.d/server/server"
elif [[ $(command -v emacs) ]]; then
    EDIT="emacs"
elif [[ $(command -v vim) ]]; then
    EDIT="vim"
fi

case "$TERM" in
    eterm-color)
	EDIT="emacsclient --server-file $HOME/.emacs.d/server/remote -T/ssh:$(hostname):"
esac

# this will override the previous setting (so a local emacs will take priority)
case "$INSIDE_EMACS" in
    *term*)
	EDIT="emacsclient --server-file $HOME/.emacs.d/server/server"
esac

$EDIT $*
