#!/usr/bin/env python3

import json
import sys

if __name__ == '__main__':
    secrets = json.load(open("secrets.json"))

    contents = sys.stdin.read()
    for name, value in secrets.items():
        contents = contents.replace(value, f"`{name}`")

    sys.stdout.write(contents)
