#!/usr/bin/env bash

if [[ $(command -v emacsclient) ]]; then
    emacsclient -T "/ssh:$(hostname):" -f ~/.remote-emacs-server $@
else
    echo "falling back to nowait emacsclient stub..."

    dir="/ssh:$(hostname):$(pwd)";

    files=""
    for file in $*; do
        files="${files} -file ${file}"
    done

    echo "-auth emacskeyemacskeyemacskeyemacskeyemacskeyemacskeyemacskeyemacskey -dir ${dir} -nowait -current-frame -tty /dev/ttys001 xterm-256color ${files}" | nc localhost 40000
fi
