#!/usr/bin/env bash

EDIT="vi"

if [[ $(command -v emacsclient) ]]; then
    if [ ! -z "$SSH_TTY" ]; then
        EDIT="emacsclient -a '' --server-file $HOME/.emacs.d/server/server -T/ssh:$(hostname):";
    else
        EDIT="emacsclient -a '' --server-file $HOME/.emacs.d/server/server";
    fi
elif [[ $(command -v emacs) ]]; then
    EDIT="emacs"
elif [[ $(command -v vim) ]]; then
    EDIT="vim"
fi

# this will override the previous setting (so a local emacs will take priority)
case "$INSIDE_EMACS" in
    *term*)
	EDIT="emacsclient --server-file $HOME/.emacs.d/server/server"
esac

$EDIT $*
