name: Build

on:
  push:

jobs:

  build-macos-env:
    name: Build
    runs-on: macos-11

    steps:

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Clean existing install
      run: |
        brew bundle cleanup --force

    - name: Ignore MAS apps
      run: sed -i bak -e 's/^mas/#mas/g' Brewfile

    - name: Make
      run: make
