# very slightly tweaked from https://github.com/malob/nixpkgs/blob/2772db984cc17320360b30c77c6f6a007ecefb4f/.github/workflows/ci.yml
# changes: cachix name, remove nix-darwin specific stuff

name: Build nix environments

on:
  push:

jobs:

  build-macos-env:
    name: Build/cache macOS Nix env
    runs-on: macos-10.15

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Nix
      uses: cachix/install-nix-action@v16

    - name: Setup Cachix
      uses: cachix/cachix-action@v10
      with:
        name: nuance
        extraPullNames: nix-community
        signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}

    - name: Run cachix in the background
      run: |
        cachix watch-store nuance &

    - name: Block files
      run: |
        for file in $(find . -ipath '**/secrets/*.nix'); do echo '{...}: {}' > $file; done
        echo '{...}: {}' > nixos/machines/dl/cuda.nix

    - name: Check flake
      run: |
        nix flake check

    - name: Build home-manager config
      run: |
        # Prevent conflict between Cachix installed by workflow and the one installed in the config
        nix-env --set-flag priority 1 cachix
        nix build --verbose --show-trace .#homeConfigurations.github-macos-ci.activationPackage -o github-macos-ci
        nix build --verbose --show-trace .#homeConfigurations.macos-bootstrap.activationPackage -o macos-bootstrap

    - name: Activate home-manager environment
      run: |
        HOME_MANAGER_BACKUP_EXT=backup ./github-macos-ci/activate
        HOME_MANAGER_BACKUP_EXT=backup ./macos-bootstrap/activate

  build-nixos-env:
    name: Build/cache linux nixos env
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Nix
      uses: cachix/install-nix-action@v16

    - name: Setup Cachix
      uses: cachix/cachix-action@v10
      with:
        name: nuance
        extraPullNames: nix-community
        signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}

    - name: Run cachix in the background
      run: |
        cachix watch-store nuance &

    - name: Block certain files
      run: |
        for file in $(find . -ipath '**/secrets/*.nix'); do echo '{...}: {}' > $file; done
        echo '{...}: {}' > nixos/machines/dl/cuda.nix

    - name: Check flake
      run: |
        nix flake check

    - name: Build nixos configuration
      run: |
        # Prevent conflict between Cachix installed by workflow and the one installed in the config
        nix-env --set-flag priority 1 cachix
        nix build --verbose --show-trace .#nixosConfigurations.dl.config.system.build.toplevel
        nix build --verbose --show-trace .#nixosConfigurations.vpn.config.system.build.toplevel
