# very slightly tweaked from https://github.com/malob/nixpkgs/blob/2772db984cc17320360b30c77c6f6a007ecefb4f/.github/workflows/ci.yml
# changes: cachix name, remove nix-darwin specific stuff

name: Build Nix envs

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # Every Sunday at midnight UTC

jobs:

  build-macos-env:
    name: Build/cache macOS Nix env
    runs-on: macos-latest
    if: ${{ ! (github.event_name == 'workflow_dispatch' || github.event_name == 'schedule') }}

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Nix
      uses: cachix/install-nix-action@v13
      with:
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20210429_d15a196/install
        extra_nix_config: |
          experimental-features = nix-command flakes

    - name: Setup Cachix
      uses: cachix/cachix-action@v10
      with:
        name: nuance
        extraPullNames: nix-community
        signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}

    - name: Build home-manager config
      run: |
        # Prevent conflict between Cachix installed by workflow and the one installed in the config
        nix-env --set-flag priority 1 cachix
        cd home-manager
        nix build --verbose --show-trace .#homeConfigurations.github-macos-ci.activationPackage -o github-macos-ci
        nix build --verbose --show-trace .#homeConfigurations.macos-bootstrap.activationPackage -o macos-bootstrap

    - name: Activate home-manager environment
      run: |
        cd home-manager
        HOME_MANAGER_BACKUP_EXT=backup ./github-macos-ci/activate
        HOME_MANAGER_BACKUP_EXT=backup ./macos-bootstrap/activate

  build-linux-env:
    name: Build/cache linux Nix env
    runs-on: ubuntu-latest
    if: ${{ ! (github.event_name == 'workflow_dispatch' || github.event_name == 'schedule') }}

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Nix
      uses: cachix/install-nix-action@v13
      with:
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20210429_d15a196/install
        extra_nix_config: |
          experimental-features = nix-command flakes

    - name: Setup Cachix
      uses: cachix/cachix-action@v10
      with:
        name: nuance
        extraPullNames: nix-community
        signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}

    - name: Build home-manager config
      run: |
        # Prevent conflict between Cachix installed by workflow and the one installed in the config
        nix-env --set-flag priority 1 cachix
        cd home-manager
        nix build --verbose --show-trace .#homeConfigurations.github-linux-ci.activationPackage

    - name: Activate home-manager environment
      run: |
        cd home-manager
        HOME_MANAGER_BACKUP_EXT=backup ./result/activate

  build-nixos-env:
    name: Build/cache linux nixos env
    runs-on: ubuntu-latest
    if: ${{ ! (github.event_name == 'workflow_dispatch' || github.event_name == 'schedule') }}

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Nix
      uses: cachix/install-nix-action@v13
      with:
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20210429_d15a196/install
        extra_nix_config: |
          experimental-features = nix-command flakes

    - name: Setup Cachix
      uses: cachix/cachix-action@v10
      with:
        name: nuance
        extraPullNames: nix-community
        signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}

    - name: Build nixos configuration
      run: |
        # Prevent conflict between Cachix installed by workflow and the one installed in the config
        nix-env --set-flag priority 1 cachix
        cd nixos
        echo '{...}: {}' > machines/dl/secrets/wifi.nix
        echo '{...}: {}' > machines/dl/cuda.nix
        nix build --verbose --show-trace .#nixosConfigurations.dl.config.system.build.toplevel

  stage-update:
    name: Stage new version
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' }}

    outputs:
      home-manager-lock: ${{ steps.lock-files.outputs.home_manager_lock }}
      nixos-lock: ${{ steps.lock-files.outputs.nixos_lock }}

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Nix
      uses: cachix/install-nix-action@v13
      with:
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20210429_d15a196/install
        extra_nix_config: |
          experimental-features = nix-command flakes

    - name: Update inputs
      id: lock-files
      run: |
        cd home-manager
        nix flake lock --recreate-lock-file
        echo "::set-output name=home_manager_lock::$(cat flake.lock | jq -cM .)"

        cd ../nixos
        nix flake lock --recreate-lock-file
        echo "::set-output name=nixos_lock::$(cat flake.lock | jq -cM .)"

  build-updated-macos-env:
    name: Build/cache macOS Nix env
    runs-on: macos-latest
    needs: stage-update

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Nix
      uses: cachix/install-nix-action@v13
      with:
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20210429_d15a196/install
        extra_nix_config: |
          experimental-features = nix-command flakes

    - name: Setup Cachix
      uses: cachix/cachix-action@v10
      with:
        name: nuance
        extraPullNames: nix-community
        signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}

    - name: Build home-manager config
      run: |
        # Prevent conflict between Cachix installed by workflow and the one installed in the config
        nix-env --set-flag priority 1 cachix
        cd home-manager
        echo '${{ needs.stage-update.outputs.home-manager-lock }}' | jq -M . > flake.lock

        nix build --verbose --show-trace .#homeConfigurations.github-macos-ci.activationPackage -o github-macos-ci
        nix build --verbose --show-trace .#homeConfigurations.macos-bootstrap.activationPackage -o macos-bootstrap

    - name: Activate home-manager environment
      run: |
        cd home-manager
        HOME_MANAGER_BACKUP_EXT=backup ./github-macos-ci/activate
        HOME_MANAGER_BACKUP_EXT=backup ./macos-bootstrap/activate

  build-updated-linux-env:
    name: Build/cache linux Nix env
    runs-on: ubuntu-latest
    needs: stage-update

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Nix
      uses: cachix/install-nix-action@v13
      with:
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20210429_d15a196/install
        extra_nix_config: |
          experimental-features = nix-command flakes

    - name: Setup Cachix
      uses: cachix/cachix-action@v10
      with:
        name: nuance
        extraPullNames: nix-community
        signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}

    - name: Build home-manager config
      run: |
        # Prevent conflict between Cachix installed by workflow and the one installed in the config
        nix-env --set-flag priority 1 cachix
        cd home-manager
        echo '${{ needs.stage-update.outputs.home-manager-lock }}' | jq -M . > flake.lock

        nix build --verbose --show-trace .#homeConfigurations.github-linux-ci.activationPackage

    - name: Activate home-manager environment
      run: |
        cd home-manager
        HOME_MANAGER_BACKUP_EXT=backup ./result/activate

  build-updated-nixos-env:
    name: Build/cache linux nixos env
    runs-on: ubuntu-latest
    needs: stage-update

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Nix
      uses: cachix/install-nix-action@v13
      with:
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20210429_d15a196/install
        extra_nix_config: |
          experimental-features = nix-command flakes

    - name: Setup Cachix
      uses: cachix/cachix-action@v10
      with:
        name: nuance
        extraPullNames: nix-community
        signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}

    - name: Build nixos configuration
      run: |
        # Prevent conflict between Cachix installed by workflow and the one installed in the config
        nix-env --set-flag priority 1 cachix
        cd nixos
        echo '${{ needs.stage-update.outputs.nixos-lock }}' | jq -M . > flake.lock

        echo '{...}: {}' > machines/dl/secrets/wifi.nix
        echo '{...}: {}' > machines/dl/cuda.nix
        nix build --verbose --show-trace .#nixosConfigurations.dl.config.system.build.toplevel

  commit-update:
    name: Commit updated nix.lock
    runs-on: ubuntu-latest
    needs: [ stage-update, build-updated-macos-env, build-updated-linux-env, build-updated-nixos-env ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Push commit with updated inputs
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

        echo '${{ needs.stage-update.outputs.home-manager-lock }}' | jq -M . > home-manager/flake.lock
        echo '${{ needs.stage-update.outputs.nixos-lock }}' | jq -M . > nixos/flake.lock

        git add home-manager/flake.lock
        git add nixos/flake.lock
        git commit -m "Update inputs"

        git push
