name: Build

on:
  push:

jobs:

  build-macos-env:
    name: Build
    runs-on: macos-11

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure Homebrew cache
      uses: actions/cache@v2
      with:
        path: |
          ~/Library/Caches/Homebrew/emacs-plus*
        key: brew-${{ runner.os }}-${{ hashFiles('Brewfile.lock.json') }}

    - name: Clean existing install
      run: |
        brew bundle cleanup --force

    - name: Make
      run: make
