name: Update lockfiles

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # Every Sunday at midnight UTC

jobs:

  update:
    name: Stage new version
    runs-on: macos-11

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Clean existing install
      run: |
        brew bundle cleanup --force

    - name: Make
      run: make update

    - name: Push commit with updated inputs
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

          git commit -am "Update lockfiles"
        git push
